// const students = [
//   "Yoseob Shin",
//   "Veronica De Leon Hernandez",
//   "Tolga Kara",
//   "Sophia Hammer",
//   "Soonam Yi",
//   "Roxanne Brodylo",
//   "Olesya Steinmetz",
//   "Nadja Carina Reischel",
//   "Mohamed Abdou",
//   "Mirko Eren",
//   "Mira Vogt",
//   "Marlena Kowieska",
//   "Lorie Rocher",
//   "Logan Bacca",
//   "Khushboo Goyal",
//   "Kevin Klein",
//   "Katrin Panova",
//   "Jonathan Del Río Guzmán",
//   "Hamlet Hayrapetyan",
//   "Habid Badillo Espinosa",
//   "Gilad Tsabar",
//   "Esther Wang",
//   "Diana Thüroff",
//   "Daniela Kirilova",
//   "Daniel Papastratidis",
//   "Daniel Parry",
//   "Bas Van Der Sluis",
//   "Barbara Schulze",
//   "Anam Zehra",
// ];

// exports.students = students;
